"""Initial schema: all 17 core tables.

Creates the complete data model described in DATA_MODEL.md -- runs and their
configuration, sources/documents/chunks, reports, the evidence layer, evaluation
results and the LLM call log -- together with 40 check constraints, the unique
constraints that make deduplication work, and the indexes the benchmark queries
will need.

Autogenerated from `app.models` and reviewed. Three things worth knowing:

- Types are dialect-neutral. `sa.Uuid()` renders as native `uuid` on PostgreSQL and
  `CHAR(32)` on SQLite; `sa.DateTime(timezone=True)` as `timestamptz`. That is what
  lets the test suite run this exact migration rather than a stand-in.
- Enums are VARCHAR + CHECK, not PostgreSQL ENUM types, so adding a member later is
  a data migration rather than a DDL one.
- Every unique constraint is named `uq_<table>_...`. Constraint names are
  schema-scoped in PostgreSQL, so two tables cannot share one -- an earlier version
  of this migration failed part-way through on a real server for exactly that
  reason. `tests/integration/test_schema_portability.py` now asserts global
  uniqueness of every constraint and index name.

This migration inserts no rows. The schema ships empty -- see DATA_MODEL.md,
"No seed data".

Revision ID: 253b523fd670
Revises: (none -- this is the first)
Create Date: 2026-10-06

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253b523fd670'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('benchmark_run',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('topic_set', sa.String(length=200), nullable=False),
    sa.Column('topic_set_version', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_run'))
    )
    op.create_table('run_configuration',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.Enum('model_only', 'hybrid', 'search_grounded', name='researchmode', native_enum=False, length=40), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('max_subquestions', sa.Integer(), nullable=False),
    sa.Column('max_sources', sa.Integer(), nullable=False),
    sa.Column('planner_prompt_version', sa.String(length=40), nullable=True),
    sa.Column('synthesizer_prompt_version', sa.String(length=40), nullable=True),
    sa.Column('claim_prompt_version', sa.String(length=40), nullable=True),
    sa.Column('verifier_prompt_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('chunk_overlap IS NULL OR chunk_size IS NULL OR chunk_overlap < chunk_size', name=op.f('ck_run_configuration_overlap_smaller_than_chunk')),
    sa.CheckConstraint('max_sources > 0', name=op.f('ck_run_configuration_max_sources_positive')),
    sa.CheckConstraint('max_subquestions > 0', name=op.f('ck_run_configuration_max_subquestions_positive')),
    sa.CheckConstraint('temperature >= 0 AND temperature <= 2', name=op.f('ck_run_configuration_temperature_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_configuration'))
    )
    with op.batch_alter_table('run_configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_configuration_fingerprint'), ['fingerprint'], unique=True)

    op.create_table('source',
    sa.Column('source_type', sa.Enum('web', 'academic', 'model', name='sourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('first_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source_type = 'model' OR url IS NOT NULL OR doi IS NOT NULL OR external_id IS NOT NULL", name=op.f('ck_source_external_sources_are_identifiable')),
    sa.CheckConstraint('citation_count IS NULL OR citation_count >= 0', name=op.f('ck_source_citation_count_non_negative')),
    sa.CheckConstraint('publication_year IS NULL OR (publication_year > 1400 AND publication_year < 2200)', name=op.f('ck_source_publication_year_plausible')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source'))
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index('ix_source_doi', ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_fingerprint'), ['fingerprint'], unique=True)

    op.create_table('document',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('char_length', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Enum('snippet', 'abstract', 'full_text', name='evidencedepth', native_enum=False, length=40), nullable=False),
    sa.Column('extractor', sa.String(length=60), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('char_length > 0', name=op.f('ck_document_char_length_positive')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_document_source_id_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_document_content_per_source')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_content_hash'), ['content_hash'], unique=False)

    op.create_table('research_run',
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('normalized_topic', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'planning', 'retrieving', 'drafting', 'verifying', 'completed', 'failed', name='runstatus', native_enum=False, length=40), nullable=False),
    sa.Column('configuration_id', sa.Uuid(), nullable=False),
    sa.Column('benchmark_run_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status <> 'failed' OR error_code IS NOT NULL", name=op.f('ck_research_run_failed_runs_have_an_error_code')),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_research_run_completed_after_started')),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_run.id'], name=op.f('fk_research_run_benchmark_run_id_benchmark_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['configuration_id'], ['run_configuration.id'], name=op.f('fk_research_run_configuration_id_run_configuration'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_run'))
    )
    with op.batch_alter_table('research_run', schema=None) as batch_op:
        batch_op.create_index('ix_research_run_benchmark_configuration', ['benchmark_run_id', 'configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_run_normalized_topic'), ['normalized_topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_run_status'), ['status'], unique=False)

    op.create_table('document_chunk',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('end_char > start_char', name=op.f('ck_document_chunk_span_is_non_empty')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_document_chunk_position_non_negative')),
    sa.CheckConstraint('start_char >= 0', name=op.f('ck_document_chunk_start_char_non_negative')),
    sa.CheckConstraint('token_count IS NULL OR token_count > 0', name=op.f('ck_document_chunk_token_count_positive')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_chunk_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunk')),
    sa.UniqueConstraint('document_id', 'position', name='uq_document_chunk_position_per_document')
    )
    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunk_content_hash'), ['content_hash'], unique=False)

    op.create_table('evaluation_result',
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.Enum('claim_support_rate', 'hallucination_rate', 'citation_precision', 'citation_recall', 'fabrication_rate', 'coverage', 'source_diversity', 'full_text_grounding_rate', 'conflicts_detected', 'total_tokens', 'cost_usd', 'wall_clock_seconds', name='metrickey', native_enum=False, length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('numerator', sa.Integer(), nullable=True),
    sa.Column('denominator', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('metrics_version', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('denominator IS NULL OR denominator > 0', name=op.f('ck_evaluation_result_denominator_is_positive')),
    sa.CheckConstraint('numerator IS NULL OR denominator IS NULL OR numerator <= denominator', name=op.f('ck_evaluation_result_numerator_within_denominator')),
    sa.CheckConstraint('numerator IS NULL OR numerator >= 0', name=op.f('ck_evaluation_result_numerator_non_negative')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_run.id'], name=op.f('fk_evaluation_result_research_run_id_research_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_result')),
    sa.UniqueConstraint('research_run_id', 'metric_key', 'metrics_version', name='uq_evaluation_result_metric_and_version')
    )
    with op.batch_alter_table('evaluation_result', schema=None) as batch_op:
        batch_op.create_index('ix_evaluation_result_metric', ['metric_key', 'metrics_version'], unique=False)

    op.create_table('llm_call_log',
    sa.Column('research_run_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.Enum('planning', 'retrieval', 'synthesis', 'critique', 'claim_extraction', 'verification', 'citation_validation', 'conflict_detection', name='pipelinestage', native_enum=False, length=40), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(length=40), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('completion_tokens IS NULL OR completion_tokens >= 0', name=op.f('ck_llm_call_log_completion_tokens_non_negative')),
    sa.CheckConstraint('cost_usd IS NULL OR cost_usd >= 0', name=op.f('ck_llm_call_log_cost_non_negative')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_llm_call_log_latency_non_negative')),
    sa.CheckConstraint('prompt_tokens IS NULL OR prompt_tokens >= 0', name=op.f('ck_llm_call_log_prompt_tokens_non_negative')),
    sa.CheckConstraint('succeeded OR error_code IS NOT NULL', name=op.f('ck_llm_call_log_failures_have_an_error_code')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_run.id'], name=op.f('fk_llm_call_log_research_run_id_research_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call_log'))
    )
    with op.batch_alter_table('llm_call_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_llm_call_log_run_stage', ['research_run_id', 'stage'], unique=False)

    op.create_table('report',
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('word_count >= 0', name=op.f('ck_report_word_count_non_negative')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_run.id'], name=op.f('fk_report_research_run_id_research_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report')),
    sa.UniqueConstraint('research_run_id', name=op.f('uq_report_research_run_id'))
    )
    op.create_table('subquestion',
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('addressed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_subquestion_position_non_negative')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_run.id'], name=op.f('fk_subquestion_research_run_id_research_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subquestion')),
    sa.UniqueConstraint('research_run_id', 'position', name='uq_subquestion_position_per_run')
    )
    op.create_table('report_section',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('subquestion_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('end_char > start_char', name=op.f('ck_report_section_span_is_non_empty')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_report_section_position_non_negative')),
    sa.CheckConstraint('start_char >= 0', name=op.f('ck_report_section_start_char_non_negative')),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_report_section_report_id_report'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subquestion_id'], ['subquestion.id'], name=op.f('fk_report_section_subquestion_id_subquestion'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_section')),
    sa.UniqueConstraint('report_id', 'position', name='uq_report_section_position_per_report')
    )
    op.create_table('research_source',
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('subquestion_id', sa.Uuid(), nullable=True),
    sa.Column('retriever', sa.String(length=60), nullable=True),
    sa.Column('retrieval_query', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('evidence_depth', sa.Enum('snippet', 'abstract', 'full_text', name='evidencedepth', native_enum=False, length=40), nullable=False),
    sa.Column('citation_label', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('rank IS NULL OR rank >= 0', name=op.f('ck_research_source_rank_non_negative')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_run.id'], name=op.f('fk_research_source_research_run_id_research_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_research_source_source_id_source'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subquestion_id'], ['subquestion.id'], name=op.f('fk_research_source_subquestion_id_subquestion'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_source')),
    sa.UniqueConstraint('research_run_id', 'citation_label', name='uq_research_source_label_per_run'),
    sa.UniqueConstraint('research_run_id', 'source_id', name='uq_research_source_source_per_run')
    )
    op.create_table('claim',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('report_section_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_sentence', sa.Text(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('requires_citation', sa.Boolean(), nullable=False),
    sa.Column('extractor_model', sa.String(length=100), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('(start_char IS NULL AND end_char IS NULL) OR (start_char >= 0 AND end_char > start_char)', name=op.f('ck_claim_span_is_null_or_non_empty')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_claim_position_non_negative')),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_claim_report_id_report'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_section_id'], ['report_section.id'], name=op.f('fk_claim_report_section_id_report_section'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim')),
    sa.UniqueConstraint('report_id', 'position', name='uq_claim_position_per_report')
    )
    op.create_table('citation',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('marker', sa.String(length=20), nullable=False),
    sa.Column('raw_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('valid', 'broken', 'misattributed', 'fabricated', name='citationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('supporting_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(status = 'fabricated' AND source_id IS NULL) OR (status <> 'fabricated' AND source_id IS NOT NULL)", name=op.f('ck_citation_only_fabricated_citations_lack_a_source')),
    sa.CheckConstraint("status <> 'valid' OR supporting_chunk_id IS NOT NULL", name=op.f('ck_citation_valid_citations_name_a_passage')),
    sa.CheckConstraint("status = 'valid' OR failure_reason IS NOT NULL", name=op.f('ck_citation_failed_citations_have_a_reason')),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('fk_citation_claim_id_claim'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_citation_source_id_source'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supporting_chunk_id'], ['document_chunk.id'], name=op.f('fk_citation_supporting_chunk_id_document_chunk'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citation')),
    sa.UniqueConstraint('claim_id', 'marker', name='uq_citation_marker_per_claim')
    )
    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.create_index('ix_citation_status', ['status'], unique=False)

    op.create_table('evidence',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('document_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Enum('supports', 'contradicts', 'neutral', name='evidencerelation', native_enum=False, length=40), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('quote_start_char', sa.Integer(), nullable=True),
    sa.Column('quote_end_char', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('(quote_start_char IS NULL AND quote_end_char IS NULL) OR (quote_start_char >= 0 AND quote_end_char > quote_start_char)', name=op.f('ck_evidence_quote_span_is_null_or_non_empty')),
    sa.CheckConstraint('rank IS NULL OR rank >= 0', name=op.f('ck_evidence_rank_non_negative')),
    sa.CheckConstraint('similarity IS NULL OR (similarity >= 0 AND similarity <= 1)', name=op.f('ck_evidence_similarity_is_a_fraction')),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('fk_evidence_claim_id_claim'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunk.id'], name=op.f('fk_evidence_document_chunk_id_document_chunk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('claim_id', 'document_chunk_id', name='uq_evidence_chunk_per_claim')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_claim_relation', ['claim_id', 'relation'], unique=False)

    op.create_table('conflict',
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_a_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_b_id', sa.Uuid(), nullable=False),
    sa.Column('conflict_type', sa.Enum('numeric_disagreement', 'directional_disagreement', 'temporal_staleness', 'scope_mismatch', name='conflicttype', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detector_model', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_conflict_confidence_is_a_fraction')),
    sa.CheckConstraint('evidence_a_id <> evidence_b_id', name=op.f('ck_conflict_conflict_needs_two_passages')),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('fk_conflict_claim_id_claim'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_a_id'], ['evidence.id'], name=op.f('fk_conflict_evidence_a_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_b_id'], ['evidence.id'], name=op.f('fk_conflict_evidence_b_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_run.id'], name=op.f('fk_conflict_research_run_id_research_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflict')),
    sa.UniqueConstraint('evidence_a_id', 'evidence_b_id', 'conflict_type', name='uq_conflict_evidence_pair_and_type')
    )
    with op.batch_alter_table('conflict', schema=None) as batch_op:
        batch_op.create_index('ix_conflict_run_type', ['research_run_id', 'conflict_type'], unique=False)

    op.create_table('verification_result',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.Enum('supported', 'partially_supported', 'unsupported', 'contradicted', 'not_enough_evidence', name='verificationverdict', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('supporting_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('downgraded', sa.Boolean(), nullable=False),
    sa.Column('verifier_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("verdict IN ('unsupported', 'not_enough_evidence') OR supporting_evidence_id IS NOT NULL", name=op.f('ck_verification_result_evidence_bearing_verdicts_cite_evidence')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_verification_result_confidence_is_a_fraction')),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('fk_verification_result_claim_id_claim'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supporting_evidence_id'], ['evidence.id'], name=op.f('fk_verification_result_supporting_evidence_id_evidence'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_result')),
    sa.UniqueConstraint('claim_id', name=op.f('uq_verification_result_claim_id'))
    )
    with op.batch_alter_table('verification_result', schema=None) as batch_op:
        batch_op.create_index('ix_verification_result_verdict', ['verdict'], unique=False)



def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('verification_result', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_result_verdict')

    op.drop_table('verification_result')
    with op.batch_alter_table('conflict', schema=None) as batch_op:
        batch_op.drop_index('ix_conflict_run_type')

    op.drop_table('conflict')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_claim_relation')

    op.drop_table('evidence')
    with op.batch_alter_table('citation', schema=None) as batch_op:
        batch_op.drop_index('ix_citation_status')

    op.drop_table('citation')
    op.drop_table('claim')
    op.drop_table('research_source')
    op.drop_table('report_section')
    op.drop_table('subquestion')
    op.drop_table('report')
    with op.batch_alter_table('llm_call_log', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_call_log_run_stage')
        batch_op.drop_index(batch_op.f('ix_llm_call_log_request_id'))

    op.drop_table('llm_call_log')
    with op.batch_alter_table('evaluation_result', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluation_result_metric')

    op.drop_table('evaluation_result')
    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunk_content_hash'))

    op.drop_table('document_chunk')
    with op.batch_alter_table('research_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_run_status'))
        batch_op.drop_index(batch_op.f('ix_research_run_normalized_topic'))
        batch_op.drop_index('ix_research_run_benchmark_configuration')

    op.drop_table('research_run')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_content_hash'))

    op.drop_table('document')
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_fingerprint'))
        batch_op.drop_index('ix_source_doi')

    op.drop_table('source')
    with op.batch_alter_table('run_configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_configuration_fingerprint'))

    op.drop_table('run_configuration')
    op.drop_table('benchmark_run')
